### ISSUE TITLE
pip install M1 MacOS

### ISSUE THREAD

**Issue by mrivera42** [dlshriver/dnnf#9]
Has the pip installation process been tested for M1 macs? I tried installing it in a conda environment and came across the following error. 

error: Command "gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/maxrivera/miniforge3/envs/dnnf/include -arch arm64 -I/Users/maxrivera/miniforge3/envs/dnnf/include -arch arm64 -DNPY_INTERNAL_BUILD=1 -DHAVE_NPY_CONFIG_H=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -DNO_ATLAS_INFO=3 -DHAVE_CBLAS -Ibuild/src.macosx-11.0-arm64-3.8/numpy/core/src/private -Inumpy/core/include -Ibuild/src.macosx-11.0-arm64-3.8/numpy/core/include/numpy -Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/Users/maxrivera/miniforge3/envs/dnnf/include/python3.8 -Ibuild/src.macosx-11.0-arm64-3.8/numpy/core/src/private -Ibuild/src.macosx-11.0-arm64-3.8/numpy/core/src/npymath -Ibuild/src.macosx-11.0-arm64-3.8/numpy/core/src/private -Ibuild/src.macosx-11.0-arm64-3.8/numpy/core/src/npymath -Ibuild/src.macosx-11.0-arm64-3.8/numpy/core/src/private -Ibuild/src.macosx-11.0-arm64-3.8/numpy/core/src/npymath -c numpy/core/src/multiarray/alloc.c -o build/temp.macosx-11.0-arm64-cpython-38/numpy/core/src/multiarray/alloc.o -MMD -MF build/temp.macosx-11.0-arm64-cpython-38/numpy/core/src/multiarray/alloc.o.d -faltivec -I/System/Library/Frameworks/vecLib.framework/Headers" failed with exit status 1
[end of output]
note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure
× Encountered error while trying to install package.
╰─> numpy

**Comment by dlshriver** [comment]
I have not tried to install DNNF on an M1 Mac, however it is purely python so as long as the dependencies work, everything should be fine. It looks like the issue in that error message is with numpy. Does installing only numpy work, e.g., `conda install "numpy<1.22"`? One possible thing to try is to try individually installing the dependencies (listed in `requirements.txt`) and seeing which fail to install. If they do fail, it may be possible to use a more recent version, but I haven't tested with more recent versions of any dependencies yet.

**Comment by mrivera42** [comment]
That was the issue. Had to manually install specific versions of the requirements to make it work. Thanks
